### ISSUE TITLE
Version check seems to be buggy

### ISSUE THREAD

**Issue by drAlberT** [librariesio/libraries.io#877]
I have noted and investigated some strange behaviors in reporting a dependency as "out-of-date".

## 1)

It seems _**libraries.io**_ is having troubles detecting the right **_last release_** .. leading to some **false out-of-date notices** ... see this project for a live example: https://libraries.io/github/faktiva/php-redis-admin

I'm referring to the out-of-date dependencies of this project ... AFAIK **they should not be outdated** ..

Look at `php-cs-fixer` (libraries.io erroneously tells version `2.0.0-beta` is the latest), moreover it tells `symfony/debug` 3.x is the latest one (for composer.lock analysis ), but `composer.json` says that required version is "`^2.8 || ^3.0`" .. so **the used version version 2.8.13 should not be marked as outdated**, being the latest available release for 2.8 tree.
![screen-shot-2016-11-07-at-15 58 47](https://cloud.githubusercontent.com/assets/1442700/20092489/c46c1c00-a598-11e6-9488-ec14156ec98c.png)

## 2)

Another "_strange_" case is the following:

![screen shot 2016-11-08 at 09 54 02](https://cloud.githubusercontent.com/assets/1442700/20092596/51c1d7de-a599-11e6-9f77-776cd8f9299f.png)

As this repo has some misconfiguration, on packagist it has published version `1.1.0` but the very last release on GitHub is **`1.1.1`** .. my project uses the last GH release but _**libraries.io**_ tell it is "_Out of date version_" .. It has an issue, I agree, but the message should be "_warning! release in future_" or something similar ..

**Comment by keradus** [comment]
about 1st issue, IMO:
- showing beta releases under `stable` label is not nice inceed
- ^2||^3 should show ^3.... as latest, as it's bigger than ^2 and still compatible with requirements. that how semver works

**Comment by drAlberT** [comment]
@keradus I agree latest should be ^3 as per semver .. _but_ the notice should appear **both** on .json and .lock OR **neither** on one and the other .. 

Actually `symfony/debug` is out-of-date only for `composer.lock` .. and it sound strange to me

**Comment by andrew** [comment]
@drAlberT sorry about that, a case of a compound bug, they have been fixed now!

Firstly, the latest stable release of `friendsofphp/php-cs-fixer` should have been `1.13.x-dev` but because the `v` at the start wasn't been cleaned off before comparison it just picked the latest published one, this also affected comparisons, both issues fixed in https://github.com/librariesio/libraries.io/commit/ca057a7a9be6737d132d6fac67e3263ba3b543c2

The second one was something I fixed a while ago for @bengourley on projects in https://github.com/librariesio/libraries.io/issues/831 but failed to fix it for repo checks, fixed here: https://github.com/librariesio/libraries.io/commit/ca057a7a9be6737d132d6fac67e3263ba3b543c2#diff-e27b5dc7b24fe56bdd385f52ceb7ac7eL51

Both have been deployed but some results may be cached and take a little while to update.

Thanks for the bug report! 🐛

**Comment by drAlberT** [comment]
Great !! Thank you very much for your work guy :)

**Comment by drAlberT** [comment]
@andrew It seems it is still present .. at least on `composer.lock`.

PoC: https://libraries.io/github/faktiva/prestashop-clean-urls

![screen shot 2016-11-17 at 16 11 27](https://cloud.githubusercontent.com/assets/1442700/20394700/c291e35c-ace0-11e6-8dc3-c641b54770d6.png)

**Comment by andrew** [comment]
@drAlberT looks like those old "latest stable" and "latest release" versions where cached from before I fixed the bug, I've just kicked off a job to update the latest version cache for every php project, might take a little while for it to work through them all :feelsgood:

**Comment by andrew** [comment]
The previous script is still running to update 77K composer.locks, at this point I think I'll have reprocessed every php project in the database!

**Comment by drAlberT** [comment]
uhmm .. OK .. so please notify me when you think it should have OK .. so I can double check and confirm..

Thanks

**Comment by andrew** [comment]
@drAlberT all the tasks have finished now, do let me know if you notice any other related bugs

**Comment by drAlberT** [comment]
@andrew https://libraries.io/github/faktiva/prestashop-clean-urls

![screen shot 2016-11-21 at 13 14 52](https://cloud.githubusercontent.com/assets/1442700/20482413/d88be860-afec-11e6-8d80-4ed19ee4fb5f.png)

Just updated composer.lock .. but IMHO these warning shouldn't be there ... Am I bad?

**Comment by andrew** [comment]
@drAlberT those warnings are correct, you've got symfony/console and symfony/debug locked to 2.8.14 but there is a newer stable version available so out of date is correct.

**Comment by drAlberT** [comment]
@andrew uhmm .. but my `composer.json` says that **both `2.x` and `3.x` are OK**

.. so, being version **`2.8.14`** the **latest stable release for version `2.x`** I really think these warnings should not be there ..

**Comment by andrew** [comment]
If you update your composer.lock and pick up the latest 3.x the warning will go away, but it's not smart enough to know that you wish to stay a major version behind

**Comment by drAlberT** [comment]
Another issue here: https://libraries.io/packagist/facile-it%2Fparaunit-testcase

**Comment by Jean85** [comment]
Reported it as #913
